version: '3'

services:
  app:
    build:
      context: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python3 -m app'
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15.1-alpine
    restart: always
    ports:
      - "127.0.0.1:7543:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: